Repository openebs/node-disk-manager, pull requests merged in 2020-10, with the labels that each got.

#492 fix(mount): detect real device when using /dev/root
  changelogs/unreleased/492-zlymeda
  pkg/mount/mountutil.go
  pkg/mount/mountutil_test.go
Labels: Hacktoberfest, hacktoberfest-accepted

#496 fix(partition): add filesystem check on disk before creating partitions
  changelogs/unreleased/496-akhilerm
  pkg/partition/partition.go
Labels: pr/hold-merge

#494 feat(partition): Add label as meta info for partitions
  pkg/partition/partition.go
  pkg/partition/partition_test.go
Labels: Hacktoberfest
